apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: ecommerce
  MYSQL_PASSWORD: ecommerce
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin
