apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: ConfigMap
      name: ecommerce-config
    path: patch-configmap-dev.yaml
  - path: patch-api-gateway-dev.yaml
  - path: patch-product-service-dev.yaml
  - path: patch-order-service-dev.yaml
  - path: patch-inventory-service-dev.yaml
  - path: patch-notification-service-dev.yaml
