apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SHOP_ORIGIN: "https://shop.example.com"
  ADMIN_ORIGIN: "https://admin.example.com"
